$ErrorActionPreference = "Stop"

Write-Host "Press any key to start the installation..."
[void][System.Console]::ReadKey($true)

$installpath = "C:\Users\$env:USERNAME\AppData\Local\Dichromate\Application"

Write-Host "Checking for Dichromate installation... " -NoNewline

if (!(Test-Path $installpath)) {
    Write-Host "NOT FOUND" -ForegroundColor Red
    $dichromate = Read-Host -Prompt "Would you like to install Dichromate(Y/N): "
    if (($dichromate -eq "Y") -or ($dichromate -eq "y")) {
        $originalCSV = curl.exe -s https://omahaproxy.appspot.com/all?csv=1 | ConvertFrom-Csv -Delimiter "," | Select-String "os=win; channel=stable"
        $removeWhitespace = $originalCSV -split "\s+"
        $selectVersionpart = $removeWhitespace[2]
        $removeVariable = $selectVersionpart -split "="
        $almostdone = $removeVariable[1]
        $version = $almostdone -replace ';',""
        Set-Location $PSScriptRoot
        Write-Host "Downloading the installer"
        curl.exe -O -L https://github.com/Dichromate-Browser/Dichromate/releases/download/$version/dichromate-$version.exe
        Write-Host "Running the installer"
        .\dichromate-$version.exe
        Write-Host "Please re-run the setup now."
        Exit
    }
    else {
        Write-Host "Dichromate is required for this to work."
        Exit
    }
}

else {
    Write-Host "OK" -ForegroundColor Green
}

$untrustedpath = "C:\Users\$env:USERNAME\Downloads\Untrusted Files"

if (!(Test-Path $untrustedpath)) {
    New-Item -ItemType Directory -Path $untrustedpath | Out-Null
}

Write-Host "Copying source files..." -NoNewline

Set-Location $PSScriptRoot
curl.exe -s -O https://raw.githubusercontent.com/Dichromate-Browser/Dichromate-Windows-Sandbox/main/dichromate-sandbox.ico
curl.exe -s -O https://raw.githubusercontent.com/Dichromate-Browser/Dichromate-Windows-Sandbox/main/dichromate.wsb

Copy-Item -Path (Join-Path $PSScriptRoot dichromate.wsb) $installpath -Force

Copy-Item -Path (Join-Path $PSScriptRoot dichromate-sandbox.ico) $installpath -Force

Write-Host "Done" -ForegroundColor Green 

Write-Host "Generating a WSB file for your system... " -NoNewline

$File = Join-Path $installpath dichromate.wsb

$lineNumber = 6
$textToAdd = "          <HostFolder>$installpath</HostFolder>"
$fileContent = Get-Content $File
$fileContent[$lineNumber-1] = $textToAdd
$fileContent | Set-Content $File

$lineNumber2 = 11
$textToAdd = "          <HostFolder>$untrustedpath</HostFolder>"
$fileContent = Get-Content $File
$fileContent[$lineNumber2-1] = $textToAdd
$fileContent | Set-Content $File

$NewContent = Get-Content -Path $File |
    ForEach-Object {
        $_

        if($_ -match ('^' + [regex]::Escape("<Configuration>"))) {
            "<!--Generated by install.exe-->"
        }
    } 

$NewContent | Out-File -FilePath $File -Encoding Default -Force

Write-Host "Done" -ForegroundColor Green 

Write-Host "Adding Desktop and Start Menu shortcuts... " -NoNewline

$WshShell = New-Object -comObject WScript.Shell
$Shortcut = $WshShell.CreateShortcut("C:\Users\$env:USERNAME\Desktop\Dichromate Sandbox.lnk")
$Shortcut.TargetPath = Join-Path $installpath dichromate.wsb
$Shortcut.IconLocation = Join-Path $installpath dichromate-sandbox.ico
$Shortcut.Save()

$WshShell = New-Object -comObject WScript.Shell
$Shortcut = $WshShell.CreateShortcut("C:\Users\$env:USERNAME\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Dichromate-Sandbox.lnk")
$Shortcut.TargetPath = Join-Path $installpath dichromate.wsb
$Shortcut.IconLocation = Join-Path $installpath dichromate-sandbox.ico
$Shortcut.Save()

Write-Host "Done" -ForegroundColor Green 

Write-Host "The installation has completed successfully" -ForegroundColor Green
Write-Host "Press any key to exit..."
[void][System.Console]::ReadKey($true)
